### ISSUE TITLE
restart on reboot? (Prysm guide)

### ISSUE THREAD

**Issue by fireheadman** [nbarrientos/cryptowat_exporter#4]
I found the use of your cryptowat_exporter in a guide from Prysm labs.
REF:  https://docs.prylabs.network/docs/prysm-usage/monitoring/currency-converter/#update-prometheus-configuration

I do not see anything that would explain/show how this binary starts up on a reboot.  (Ubuntu 20)
Also not seeing any changes in the ETH Stakers grafana dashboard to reflect this addition

Should be something like this:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/19847195/100550946-e36d1180-323a-11eb-9ef6-094e838de272.png">

Would you be able to shed a little light on this?
Thanks

**Comment by nbarrientos** [comment]
Hi,

Sorry but the project does not provide any facility to run the exporter at boot time. You can write your own upstart or systemd configurations. Users using Docker can use stuff like Docker compose. I'd suggest to contact the authors of the instructions you're referencing to see if they can help you with this :)
