### ISSUE TITLE
Getting "Unable to get information for market bitstamp:ethxxx"

### ISSUE THREAD

**Issue by fireheadman** [nbarrientos/cryptowat_exporter#7]
If there is something I can try to resolve this, please let me know.
This was working flawlessly all last week.   

```
user@system:~/dist$ sudo systemctl status cryptowat
● cryptowat.service - cryptowat go client
     Loaded: loaded (/etc/systemd/system/cryptowat.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-12-07 19:20:36 UTC; 9min ago
   Main PID: 2236 (cryptowat_expor)
      Tasks: 14 (limit: 38436)
     Memory: 11.7M
     CGroup: /system.slice/cryptowat.service
             └─2236 /usr/local/bin/cryptowat_exporter --cryptowat.pairs=etheur,ethusd,ethgbp,ethcad,ethchf,ethjpy,ethbtc

Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Unable to get information for market bitstamp:ethgbp
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Looking for market bitstamp:ethcad
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Unable to get information for market bitstamp:ethcad
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Looking for market bitstamp:ethchf
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Unable to get information for market bitstamp:ethchf
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Looking for market bitstamp:ethjpy
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Unable to get information for market bitstamp:ethjpy
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Looking for market bitstamp:ethbtc
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Unable to get information for market bitstamp:ethbtc
Dec 07 19:29:37 system cryptowat_exporter[2236]: 2020/12/07 19:29:37 Sleeping for 60 seconds
```

**Comment by fireheadman** [comment]
![image](https://user-images.githubusercontent.com/19847195/101396255-48061d00-3888-11eb-8748-c51399d990d8.png)

**Comment by fireheadman** [comment]
This appears to be happening for all markets (bitstamp, kraken, coinbase-pro)

**Comment by nbarrientos** [comment]
Hi,

Thanks for your report. The plugin works for me, though. Please make sure that:

1) You're running the latest version published (`v2.1.1`)
2) You're selecting a reasonable polling interval (`--cryptowat.cacheseconds`) so you don't exceed the daily free API credits (see the [README ](https://github.com/nbarrientos/cryptowat_exporter/blob/master/README.md) for more details).

**Comment by chrispersonal** [comment]
Am also getting this same issue. Restarted my server running cryptowat and suddenly getting this. Running latest version and cacheseconds set to default (60s).

**Comment by nbarrientos** [comment]
Hi,

The default value for `--cryptowat.cacheseconds` is 300 seconds since `v2.1.0` which is enough to not to exceed the [free daily API quota](https://docs.cryptowat.ch/rest-api/rate-limit#api-request-pricing-structure).

In my case I'm running the exporter continuously with the default cache validity fetching three exchanges and two pairs and it works. I've just restarted it and it's happily retrieving values:

```
cryptowat_exporter    | 2020/12/08 15:49:38 Looking for market bitstamp:btcusd
cryptowat_exporter    | 2020/12/08 15:49:38 Looking for market bitstamp:ltcusd
cryptowat_exporter    | 2020/12/08 15:49:38 Looking for market kraken:btcusd
cryptowat_exporter    | 2020/12/08 15:49:38 Looking for market kraken:ltcusd
cryptowat_exporter    | 2020/12/08 15:49:38 Looking for market coinbase-pro:btcusd
cryptowat_exporter    | 2020/12/08 15:49:38 Looking for market coinbase-pro:ltcusd
cryptowat_exporter    | 2020/12/08 15:49:38 Sleeping for 900 seconds
```

![image](https://user-images.githubusercontent.com/131893/101499770-f0da7800-396d-11eb-9fa0-47f519d35d62.png)

Please make sure that you're running the latest version and that you're not overriding the default cache validity. If you have been banned in the worst case your quota will be restablished within 24h.

This is all assuming that it's a quota problem. Please make sure as well that the node running the exporter can talk to `api.cryptowat.ch` via HTTPS, etc.

**Comment by fireheadman** [comment]
thanks for the tip on cacheseconds... I have increased to 1800s (30min) intervals as I am not overly concerned with fluxuation.
```

● cryptowat.service - cryptowat go client
     Loaded: loaded (/etc/systemd/system/cryptowat.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-12-08 16:50:29 UTC; 5s ago
   Main PID: 8834 (cryptowat_expor)
      Tasks: 10 (limit: 38436)
     Memory: 17.1M
     CGroup: /system.slice/cryptowat.service
             └─8834 /usr/local/bin/cryptowat_exporter --cryptowat.pairs=ethusd,ethbtc --cryptowat.exchanges=kraken --cryptowat.cacheseconds=1800

Dec 08 16:50:29 eth01 systemd[1]: Started cryptowat go client.
Dec 08 16:50:29 eth01 cryptowat_exporter[8834]: 2020/12/08 16:50:29 Listening on address :9745
Dec 08 16:50:29 eth01 cryptowat_exporter[8834]: 2020/12/08 16:50:29 Looking for market kraken:ethusd
Dec 08 16:50:29 eth01 cryptowat_exporter[8834]: 2020/12/08 16:50:29 Looking for market kraken:ethbtc
Dec 08 16:50:29 eth01 cryptowat_exporter[8834]: 2020/12/08 16:50:29 Sleeping for 1800 seconds
```

free to close at will.

**Comment by fireheadman** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/19847195/101514998-1d28d100-393b-11eb-8185-03bcd05666af.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/19847195/101515020-24e87580-393b-11eb-8f37-80edbd711bee.png">

**Comment by GuillaumeMiralles** [comment]
Hey fireheadman!

Glad you have resolved your issue. I hope you enjoy the dashboard AND @nbarrientos tool :D
